In [1]:
from GameClass import Game
from Agent import Agent
import numpy as np
import os
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')


misha_playing = True #Bot vs human play
learning = True #Specifies whether the experience is added to the replay buffer

pygame 2.5.2 (SDL 2.28.3, Python 3.12.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/michal.maslowski/Desktop/GitHub/OvercookedAI-coop/Graphics
2.18.0


In [2]:
if learning:    
    number_updates = 32 #The power of 2 that is the closest to the time contraints on Kaggle.  64
    ticks_per_game = 2**13 # 2^13, Circa 2.25 minutes of gameplay
    games_per_update = 5 #5
    number_of_games = number_updates * games_per_update
    
else:
    number_of_games = 1
    time_per_game = int(input("Please enter the length of the game, in seconds (default: 180)"))
    ticks_per_game = time_per_game * 60

if misha_playing:
    Misha = Agent(learning, save_file="Misha.keras", initialize=True) 
    
losses = []
file_sizes = []
    
for game_no in range (number_of_games):    
    GameObj = Game(misha_playing, ticks_per_game, agent = Misha if misha_playing else None) 
    GameObj.run()
    
    file_size_mb = os.path.getsize("data.tfrecord") / (1024 * 1024)
    file_sizes.append(file_size_mb)
    np.save("file_sizes", file_sizes)
    
    if learning and (((game_no + 1) % games_per_update) == 0):
        l = Misha.train_on_moves()
        logging.info(f"losses after training: {l}")
        losses.extend(l)
        np.save("losses.npy", losses)

/Users/michal.maslowski/Library/Python/3.12/lib/python/site-packages/keras/src/saving/saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 16 variables whereas the saved optimizer has 20 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))
2025-01-19 22:34:16.544 Python[85427:4252600] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2025-01-19 22:34:20.668080: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:370] TFRecordDataset `buffer_size` is unspecified, default to 262144


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-49263542000.0, shape=(), dtype=float32) tf.Tensor(-0.054659616, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:21.052186: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-47064154000.0, shape=(), dtype=float32) tf.Tensor(-0.055238638, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:21.372008: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-01-19 22:34:21,720 - DEBUG - Creating converter from 5 to 3
2025-01-19 22:34:21,762 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=901278597120.0>, <tf.Tensor: shape=(), dtype=float32, numpy=852015120384.0>, <tf.Tensor: shape=(), dtype=float32, numpy=804950966272.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-44839470000.0, shape=(), dtype=float32) tf.Tensor(-0.055704597, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-54518940000.0, shape=(), dtype=float32) tf.Tensor(-0.053615972, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:25.796418: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-52301136000.0, shape=(), dtype=float32) tf.Tensor(-0.05434886, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:26,448 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1016841371648.0>, <tf.Tensor: shape=(), dtype=float32, numpy=962322563072.0>, <tf.Tensor: shape=(), dtype=float32, numpy=910021558272.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-49882990000.0, shape=(), dtype=float32) tf.Tensor(-0.054815173, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-42999350000.0, shape=(), dtype=float32) tf.Tensor(-0.06295787, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-40928346000.0, shape=(), dtype=float32) tf.Tensor(-0.063951865, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:30.562726: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-01-19 22:34:30,896 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=682986110976.0>, <tf.Tensor: shape=(), dtype=float32, numpy=639986761728.0>, <tf.Tensor: shape=(), dtype=float32, numpy=599058415616.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-38830540000.0, shape=(), dtype=float32) tf.Tensor(-0.064819284, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-49452680000.0, shape=(), dtype=float32) tf.Tensor(-0.0470143, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-47613020000.0, shape=(), dtype=float32) tf.Tensor(-0.047498457, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:35,193 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1051864596480.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1002411917312.0>, <tf.Tensor: shape=(), dtype=float32, numpy=954798964736.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-45585400000.0, shape=(), dtype=float32) tf.Tensor(-0.047743455, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-55519085000.0, shape=(), dtype=float32) tf.Tensor(-0.045346104, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-53467546000.0, shape=(), dtype=float32) tf.Tensor(-0.04574482, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:39,437 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1224340799488.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1168821846016.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1115354300416.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-51185123000.0, shape=(), dtype=float32) tf.Tensor(-0.04589136, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-55637900000.0, shape=(), dtype=float32) tf.Tensor(-0.060195852, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:42.975302: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-53354693000.0, shape=(), dtype=float32) tf.Tensor(-0.061423007, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:43,587 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=924281339904.0>, <tf.Tensor: shape=(), dtype=float32, numpy=868643438592.0>, <tf.Tensor: shape=(), dtype=float32, numpy=815288745984.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-50914853000.0, shape=(), dtype=float32) tf.Tensor(-0.062450085, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-56408867000.0, shape=(), dtype=float32) tf.Tensor(-0.059486657, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-54023750000.0, shape=(), dtype=float32) tf.Tensor(-0.060574796, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:47,542 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=948260831232.0>, <tf.Tensor: shape=(), dtype=float32, numpy=891851964416.0>, <tf.Tensor: shape=(), dtype=float32, numpy=837828149248.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-51414960000.0, shape=(), dtype=float32) tf.Tensor(-0.06136695, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-51642827000.0, shape=(), dtype=float32) tf.Tensor(-0.05843756, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-49358570000.0, shape=(), dtype=float32) tf.Tensor(-0.05931923, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:51,645 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=883726614528.0>, <tf.Tensor: shape=(), dtype=float32, numpy=832083787776.0>, <tf.Tensor: shape=(), dtype=float32, numpy=782725218304.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-46903590000.0, shape=(), dtype=float32) tf.Tensor(-0.059923444, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-57662110000.0, shape=(), dtype=float32) tf.Tensor(-0.05589006, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-55399547000.0, shape=(), dtype=float32) tf.Tensor(-0.05687582, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:34:55,937 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1031705985024.0>, <tf.Tensor: shape=(), dtype=float32, numpy=974043873280.0>, <tf.Tensor: shape=(), dtype=float32, numpy=918644326400.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-52816840000.0, shape=(), dtype=float32) tf.Tensor(-0.057494327, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-61448390000.0, shape=(), dtype=float32) tf.Tensor(-0.049898498, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-59247820000.0, shape=(), dtype=float32) tf.Tensor(-0.050638333, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:00,037 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1231467708416.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1170019188736.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1110771367936.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-56663015000.0, shape=(), dtype=float32) tf.Tensor(-0.05101231, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-66548728000.0, shape=(), dtype=float32) tf.Tensor(-0.057757225, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-63953764000.0, shape=(), dtype=float32) tf.Tensor(-0.0589074, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:03.590248: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
2025-01-19 22:35:03,951 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1152214761472.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1085666033664.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1021712269312.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-60975415000.0, shape=(), dtype=float32) tf.Tensor(-0.059679635, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-68822500000.0, shape=(), dtype=float32) tf.Tensor(-0.048310403, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-66064613000.0, shape=(), dtype=float32) tf.Tensor(-0.048728593, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:08,298 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1424589586432.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1355766956032.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1289702211584.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-62924130000.0, shape=(), dtype=float32) tf.Tensor(-0.048789658, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-77890980000.0, shape=(), dtype=float32) tf.Tensor(-0.0540927, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-75421190000.0, shape=(), dtype=float32) tf.Tensor(-0.055372775, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:12,293 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1439953584128.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1362062606336.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1286641549312.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-72333920000.0, shape=(), dtype=float32) tf.Tensor(-0.056219168, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-67911614000.0, shape=(), dtype=float32) tf.Tensor(-0.05936816, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-64508200000.0, shape=(), dtype=float32) tf.Tensor(-0.059952147, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:16,355 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1143906369536.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1075994820608.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1011486621696.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-60826976000.0, shape=(), dtype=float32) tf.Tensor(-0.060136214, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-74089366000.0, shape=(), dtype=float32) tf.Tensor(-0.047091566, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-71334100000.0, shape=(), dtype=float32) tf.Tensor(-0.047580972, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:20,527 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1573304401920.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1499214905344.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1427880804352.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-68112220000.0, shape=(), dtype=float32) tf.Tensor(-0.047701616, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-78562980000.0, shape=(), dtype=float32) tf.Tensor(-0.055128478, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-75441900000.0, shape=(), dtype=float32) tf.Tensor(-0.056027062, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:26,031 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1425088970752.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1346525986816.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1271084089344.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-71882110000.0, shape=(), dtype=float32) tf.Tensor(-0.056551814, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-77923615000.0, shape=(), dtype=float32) tf.Tensor(-0.06501064, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-74563650000.0, shape=(), dtype=float32) tf.Tensor(-0.0665328, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:30,638 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1198628667392.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1120705183744.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1046141534208.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-70933150000.0, shape=(), dtype=float32) tf.Tensor(-0.067804545, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-96778060000.0, shape=(), dtype=float32) tf.Tensor(-0.05213083, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-94053070000.0, shape=(), dtype=float32) tf.Tensor(-0.053449336, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:34,776 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1856445743104.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1759667683328.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1665614479360.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-90536540000.0, shape=(), dtype=float32) tf.Tensor(-0.05435624, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-81533600000.0, shape=(), dtype=float32) tf.Tensor(-0.0561753, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-77369180000.0, shape=(), dtype=float32) tf.Tensor(-0.056478795, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:38,848 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1451413733376.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1369880133632.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1292510953472.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-72900670000.0, shape=(), dtype=float32) tf.Tensor(-0.056402363, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-82986530000.0, shape=(), dtype=float32) tf.Tensor(-0.056025825, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-78670590000.0, shape=(), dtype=float32) tf.Tensor(-0.05626431, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:42,945 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1481219244032.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1398232580096.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1319561986048.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-73940990000.0, shape=(), dtype=float32) tf.Tensor(-0.056034498, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-124452080000.0, shape=(), dtype=float32) tf.Tensor(-0.04633709, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-121804685000.0, shape=(), dtype=float32) tf.Tensor(-0.04755495, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:47,374 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=2685798187008.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2561346109440.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2439541161984.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-117563460000.0, shape=(), dtype=float32) tf.Tensor(-0.048190806, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-106777280000.0, shape=(), dtype=float32) tf.Tensor(-0.05171894, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:51.452351: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-101245780000.0, shape=(), dtype=float32) tf.Tensor(-0.0517143, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:52,791 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=2064568287232.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1957790744576.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1856545095680.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-95131930000.0, shape=(), dtype=float32) tf.Tensor(-0.051241376, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-109555220000.0, shape=(), dtype=float32) tf.Tensor(-0.05360255, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-104106950000.0, shape=(), dtype=float32) tf.Tensor(-0.053821832, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:35:58,517 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=2043843444736.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1934288486400.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1830181535744.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-98105560000.0, shape=(), dtype=float32) tf.Tensor(-0.053604275, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-118658960000.0, shape=(), dtype=float32) tf.Tensor(-0.04830452, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-113033350000.0, shape=(), dtype=float32) tf.Tensor(-0.048349936, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:36:03,637 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=2456477237248.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2337818017792.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2224784670720.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-106554980000.0, shape=(), dtype=float32) tf.Tensor(-0.047894515, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



/Users/michal.maslowski/Library/Python/3.12/lib/python/site-packages/keras/src/models/functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['input_layer', 'input_layer_1']. Received: the structure of inputs=('*', '*')
  warnings.warn(
I0000 00:00:1737326164.550674 4252893 service.cc:148] XLA service 0x316efa6e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1737326164.551159 4252893 service.cc:156]   StreamExecutor device (0): Host, Default Version
2025-01-19 22:36:04.706814: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


I0000 00:00:1737326165.679968 4252893 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-131563780000.0, shape=(), dtype=float32) tf.Tensor(-0.0564477, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-126576620000.0, shape=(), dtype=float32) tf.Tensor(-0.057556912, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:36:10,199 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=2330719944704.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2199155900416.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2072579276800.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-120541410000.0, shape=(), dtype=float32) tf.Tensor(-0.058160096, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-103767210000.0, shape=(), dtype=float32) tf.Tensor(-0.05660507, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-97031420000.0, shape=(), dtype=float32) tf.Tensor(-0.056106616, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:36:14,463 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1833178759168.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1729411416064.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1632379863040.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-90099020000.0, shape=(), dtype=float32) tf.Tensor(-0.05519489, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-111723410000.0, shape=(), dtype=float32) tf.Tensor(-0.061158415, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/

/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-105717694000.0, shape=(), dtype=float32) tf.Tensor(-0.061640684, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



2025-01-19 22:36:19,202 - INFO - losses after training: [<tf.Tensor: shape=(), dtype=float32, numpy=1826787295232.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1715063619584.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1609345925120.0>]


/
/
/
/
/
/
/
/
/
/

new loss in a test delta:  tf.Tensor(-99304600000.0, shape=(), dtype=float32) tf.Tensor(-0.061704945, shape=(), dtype=float32)
/
/
/
/
/
/
/
/
/
/



KeyboardInterrupt: 